"""added completed boolean to todo

Revision ID: 7c788ddc33e4
Revises: bb8dc2b15a9f
Create Date: 2022-03-02 21:08:41.070498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c788ddc33e4'
down_revision = 'bb8dc2b15a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
